/* RPN MANAGEMENT SYSTEM - REGIONAL USED POPULATION */
const PopulationRegionalService=(()=>{
"use strict";
const SPREADSHEET_ID="1m9NIKo6eCYLAy_WJ_9FZlxjw2kGqcz8ey2wnm7P8CDo";
const CONFIG={
  "SURABAYA":{sheet:"POPULASI UNIT USED SURABAYA",key:"surabaya"},
  "MEDAN":{sheet:"POPULASI UNIT USED MEDAN",key:"medan"},
  "SEMARANG":{sheet:"POPULASI UNIT USED SEMARANG",key:"semarang"}
};
const ALIAS={SERIAL:["SERIAL NUMBER","SERIAL NO","SN UNIT","SN","SERIAL"],UNIT_TYPE:["UNIT TYPE","TYPE UNIT","TYPE","MODEL","UNIT"],YEAR:["YEAR","TAHUN"],HM:["HOUR METER","HM","HOUR METER UNIT"],BRANCH:["CABANG","BRANCH","LOCATION","LOKASI"],RFU:["STATUS RFU","RFU","RFU %","STATUS RFU %"],RFU_DATE:["RFU DATE","TANGGAL RFU"],ACTION:["ACTION","TINDAKAN"],BATTERY_SN:["BATTERY SN","SERIAL NUMBER BATTERY","SN BATTERY","BATTERY SERIAL"],CHARGER_SN:["CHARGER SN","SERIAL NUMBER CHARGER","SN CHARGER","CHARGER SERIAL"],BATTERY_UNIT:["BATTERY UNIT","BATTERY PASANGAN","UNIT BATTERY"],CHARGER_UNIT:["CHARGER UNIT","CHARGER PASANGAN","UNIT CHARGER"],STATUS:["STATUS","UNIT STATUS","STATUS UNIT"],CUSTOMER:["CUSTOMER","PELANGGAN"],UPDATED_AT:["UPDATED AT","LAST UPDATE","UPDATE DATE","UPDATED"],UPDATED_BY:["UPDATED BY","UPDATE BY","PIC UPDATE"]};
function norm(v){return String(v==null?"":v).trim().toUpperCase().replace(/\s+/g," ");}
function cfg(branch){const b=norm(branch);if(b==="LEMAH ABANG")return null;const c=CONFIG[b];if(!c)throw new Error("Cabang populasi belum dikonfigurasi: "+branch);return c;}
function sheet(c){const ws=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(c.sheet);if(!ws)throw new Error("Sheet '"+c.sheet+"' tidak ditemukan.");return ws;}
function map(headers){const m={};headers.forEach((h,i)=>Object.keys(ALIAS).forEach(k=>{if(ALIAS[k].some(a=>norm(a)===norm(h))&&m[k]===undefined)m[k]=i;}));return m;}
function sourceFormat(ws,values){let hr=-1;for(let r=0;r<values.length;r++)if(norm(values[r][0])==="NO"){hr=r+1;break;}if(hr<1)return{available:false};const cols=Math.max(ws.getLastColumn(),1),dr=Math.min(hr+1,Math.max(ws.getLastRow(),1));return{available:true,headerRow:hr,header:{background:ws.getRange(hr,1,1,cols).getBackgrounds()[0],fontColor:ws.getRange(hr,1,1,cols).getFontColors()[0],fontWeight:ws.getRange(hr,1,1,cols).getFontWeights()[0]},body:{background:ws.getRange(dr,1,1,cols).getBackgrounds()[0],fontColor:ws.getRange(dr,1,1,cols).getFontColors()[0]}};}
function read(branch){Auth.check();const c=cfg(branch),ws=sheet(c),v=ws.getDataRange().getValues(),h=v.length?v[0].map(String):[],u=Auth.getUser()||{};let headerRow=-1;for(let i=0;i<v.length;i++){if(norm(v[i][0])==="NO"){headerRow=i;break;}}const rows=(headerRow>=0?v.slice(headerRow+1):v.slice(1)).map((r,i)=>({ROW_NUMBER:(headerRow>=0?headerRow+2+i:i+2),VALUES:r}));return Response.success({BRANCH:branch,SHEET:c.sheet,HEADERS:h,ROWS:rows,EDITABLE:u.ROLE==="ADMIN"||u.ROLE==="SUPERVISOR",EDIT_URL:"https://docs.google.com/spreadsheets/d/"+SPREADSHEET_ID+"/edit",SOURCE_FORMAT:sourceFormat(ws,v)});}
function edit(branch,row,col,value){Auth.check();const u=Auth.getUser()||{};if(u.ROLE!=="ADMIN"&&u.ROLE!=="SUPERVISOR")throw new Error("Edit populasi hanya untuk ADMIN dan SUPERVISOR.");const ws=sheet(cfg(branch));ws.getRange(Number(row),Number(col)+1).setValue(value);SpreadsheetApp.flush();return Response.success({BRANCH:branch,ROW_NUMBER:row,COLUMN_INDEX:col});}
function updateFromRefurbish(data){if(!data)return{UPDATED:false};const b=norm(data.BRANCH);if(b==="LEMAH ABANG")return PopulationLemahAbangService.updateFromRefurbish(data);const c=cfg(data.BRANCH),ws=sheet(c),values=ws.getDataRange().getValues(),headers=values.length?values[0].map(String):[],m=map(headers),serial=norm(data.SERIAL_NUMBER||data.SN_UNIT);if(m.SERIAL===undefined||!serial)return{UPDATED:false,REASON:"SERIAL_MAPPING_NOT_FOUND"};let row=-1;for(let i=1;i<values.length;i++)if(norm(values[i][m.SERIAL])===serial){row=i+1;break;}if(row<0){row=ws.getLastRow()+1;ws.getRange(row,m.SERIAL+1).setValue(data.SERIAL_NUMBER||data.SN_UNIT);}const put=(k,v)=>{if(m[k]!==undefined&&v!==undefined&&v!=="")ws.getRange(row,m[k]+1).setValue(v);};put("UNIT_TYPE",data.UNIT_TYPE||data.TYPE_UNIT);put("YEAR",data.YEAR||data.JOB_YEAR);put("HM",data.HOUR_METER||data.HM||data.JOB_HM);put("BRANCH",data.BRANCH);put("RFU",data.RFU_PERCENT);put("RFU_DATE",data.RFU_DATE);put("ACTION",data.ACTION);put("CUSTOMER",data.CUSTOMER);put("UPDATED_AT",new Date());put("UPDATED_BY",(Auth.getUser()||{}).FULLNAME||"SYSTEM");const cat=norm(data.CATEGORY);put("STATUS",cat==="PENARIKAN UNIT"?"PENARIKAN":cat==="PENGIRIMAN UNIT"?"PENGIRIMAN":cat==="LOAN SPAREPART"?"LOAN SPAREPART":cat==="PERBAIKAN UNIT"?(Number(data.RFU_PERCENT)>=100?"RFU":"REPAIR"):"");if(cat==="PENGIRIMAN UNIT"){if(data.BATTERY_IN)put("BATTERY_SN",data.BATTERY_IN);if(data.CHARGER_SN)put("CHARGER_SN",data.CHARGER_SN);}SpreadsheetApp.flush();return{UPDATED:true,BRANCH:data.BRANCH,SHEET:c.sheet,ROW_NUMBER:row,SERIAL_NUMBER:serial};}
return{read,edit,updateFromRefurbish};})();